# Helmfile for microservices deployment
# Manages both Redis and microservices Helm releases

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # Redis dependency
  - name: redis
    namespace: default
    chart: bitnami/redis
    version: 25.2.0
    values:
      - values/redis-values.yaml
    
  # Microservices application
  - name: microservices
    namespace: default
    chart: ../helm/microservices
    needs:
      - redis
    values:
      - values/microservices-values.yaml

helmDefaults:
  wait: true
  timeout: 600
  recreatePods: false
  force: false